
import:
- source: Activiti/activiti-scripts:.travis.java.yml@dev-almerico-3212-movepropogation-to-trtavis
  mode: deep_merge 


stages:
- name: verify

jobs:
  include:
  - name: Verify build
    stage: verify
    script:
    - mvn verify -B
  
